// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_VFxXZDMwulJm0IFDdv4rx1_vLrMPNdM',
    appId: '1:10955010656:web:03c8cbbcec7e2df2ad4905',
    messagingSenderId: '10955010656',
    projectId: 'newschatapp-3a75a',
    authDomain: 'newschatapp-3a75a.firebaseapp.com',
    storageBucket: 'newschatapp-3a75a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK3k5TkwV2PT8VvoH9_RYRvVnQDSJxupM',
    appId: '1:10955010656:android:172fd9b08027bdd2ad4905',
    messagingSenderId: '10955010656',
    projectId: 'newschatapp-3a75a',
    storageBucket: 'newschatapp-3a75a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEDU8YltbfmmayAc0gwloRFAongr8Rnys',
    appId: '1:10955010656:ios:9a223712fb9f9409ad4905',
    messagingSenderId: '10955010656',
    projectId: 'newschatapp-3a75a',
    storageBucket: 'newschatapp-3a75a.firebasestorage.app',
    iosBundleId: 'com.example.newsChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEDU8YltbfmmayAc0gwloRFAongr8Rnys',
    appId: '1:10955010656:ios:9a223712fb9f9409ad4905',
    messagingSenderId: '10955010656',
    projectId: 'newschatapp-3a75a',
    storageBucket: 'newschatapp-3a75a.firebasestorage.app',
    iosBundleId: 'com.example.newsChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_VFxXZDMwulJm0IFDdv4rx1_vLrMPNdM',
    appId: '1:10955010656:web:201f680b2a3bf3a4ad4905',
    messagingSenderId: '10955010656',
    projectId: 'newschatapp-3a75a',
    authDomain: 'newschatapp-3a75a.firebaseapp.com',
    storageBucket: 'newschatapp-3a75a.firebasestorage.app',
  );
}
